version: '3.8'
services:
  web:
    image: php:8.0-apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_demo
      MYSQL_USER: mvc_demo
      MYSQL_PASSWORD: mvc_demo2004
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped