version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
#  web2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./app:/var/www/html
#    ports:
#      - "8081:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_demo
#      MYSQL_USER: mvc_demo






